package me.onionpie.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SINGLE_CHAR_RULE".
 */
public class singleCharRule {

    private Long id;
    private String ruleName;
    private String ruleDescription;
    private Boolean isRuleSetted;
    private String targetChar;
    private String destinyChar;
    private Integer selectedPosition;
    private Integer exchangePosition;

    public singleCharRule() {
    }

    public singleCharRule(Long id) {
        this.id = id;
    }

    public singleCharRule(Long id, String ruleName, String ruleDescription, Boolean isRuleSetted, String targetChar, String destinyChar, Integer selectedPosition, Integer exchangePosition) {
        this.id = id;
        this.ruleName = ruleName;
        this.ruleDescription = ruleDescription;
        this.isRuleSetted = isRuleSetted;
        this.targetChar = targetChar;
        this.destinyChar = destinyChar;
        this.selectedPosition = selectedPosition;
        this.exchangePosition = exchangePosition;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRuleName() {
        return ruleName;
    }

    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    public String getRuleDescription() {
        return ruleDescription;
    }

    public void setRuleDescription(String ruleDescription) {
        this.ruleDescription = ruleDescription;
    }

    public Boolean getIsRuleSetted() {
        return isRuleSetted;
    }

    public void setIsRuleSetted(Boolean isRuleSetted) {
        this.isRuleSetted = isRuleSetted;
    }

    public String getTargetChar() {
        return targetChar;
    }

    public void setTargetChar(String targetChar) {
        this.targetChar = targetChar;
    }

    public String getDestinyChar() {
        return destinyChar;
    }

    public void setDestinyChar(String destinyChar) {
        this.destinyChar = destinyChar;
    }

    public Integer getSelectedPosition() {
        return selectedPosition;
    }

    public void setSelectedPosition(Integer selectedPosition) {
        this.selectedPosition = selectedPosition;
    }

    public Integer getExchangePosition() {
        return exchangePosition;
    }

    public void setExchangePosition(Integer exchangePosition) {
        this.exchangePosition = exchangePosition;
    }

}
